barbar/Controllers/Customer/CustomerHomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace barbar.Controllers.Customer
{
    public class CustomerHomeController : Controller
    {
        public JsonResult customerhomedetail(){
            string username;
            try
            {
                username = HttpContext.Session["LoggedIn"].ToString();
            }
            catch (Exception e) { throw new Exception("لطفا وارد سایت شوید"); }

          try{

            Models.userContext porterage = new Models.userContext();
            Models.CustomerRequestContext request = new Models.CustomerRequestContext();
            Models.vehicleContext vehicle = new Models.vehicleContext();
            Models.packTypeContext pack = new Models.packTypeContext();
            Models.PricesContext prices = new Models.PricesContext();
            Models.DestiContext desti = new Models.DestiContext();
            Models.PorterageContext por = new Models.PorterageContext();
           
          //  int ID = (from d in porterage.barbar where d.UserName == username select d.).First();
            List<int> requestids=(from d in request.barbar where d.CustomerID==username select d.Id).ToList();
            string source = (from d in request.barbar where d.CustomerID == username select d.SourceAddress).First();
            IList<Dictionary<string , IList>> answer = new List<Dictionary<string , IList>>();
            foreach (var dd in requestids)
            {
                Dictionary<string, IList> ha = new Dictionary<string, IList>();
                IList idd = new List<int>();
                idd.Add(dd);
                    
                int porId = (from i in request.barbar where i.CustomerID == username select i.PorterageID).First();
                IList porname = (from i in por.barbar where i.Id == porId select i.Name).ToList();
                IList sourcedesti = (from d in request.barbar where d.Id == dd select new { d.SourceAddress, d.destiAddress }).ToList();
                IList status = (from d in request.barbar where d.Id == dd select d.Status).ToList();
                int vehicleid = (from d in request.barbar where d.Id == dd select d.VehicleId).First();
                IList vehicleName = (from d in vehicle.barbar where d.ID == vehicleid select new { d.Vehicle_Value, d.Vehicle_Weight }).ToList();
                int packtypeid = (from d in request.barbar where d.Id == dd select d.PackTypeId).First();
                IList packtypename = (from d in pack.barbar where d.Id == packtypeid select d.TypeName).ToList();
                IList destiId = (from d in request.barbar where d.Id == dd select d.price).ToList();
             //   IList price = (from d in prices.barbar where d.source == source && d.destination == destiId && d.vehicleID == vehicleid select d.price).ToList();
                ha.Add("SourceDesti", sourcedesti);
                ha.Add("VehicleName", vehicleName);
                ha.Add("PackType", packtypename);
                ha.Add("Price", destiId);
                ha.Add("porterageName", porname);
                ha.Add("requestid", idd);
                ha.Add("status", status);
                answer.Add(ha);
            }
                  return Json(answer, JsonRequestBehavior.AllowGet);
            }
                catch(Exception e){
                
                throw new Exception("درخواستی موجود نیست");
                }
                
            
           
    
          
        
        }




        public JsonResult customerInfo() {

            string username = HttpContext.Session["LoggedIn"].ToString();
            Models.userContext user = new Models.userContext();

            try
            {
                IList info = (from i in user.barbar where i.UserName == username select new { i.FirstName, i.LastName, i.UserName, i.PhoneNumber, i.Email, i.Address }).ToList();
                return Json(info, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e) {
                throw e;
            }
        
        
        
        }


        //
        // GET: /CustomerHome/
        [Authorize(Roles="Customer")]
        public ActionResult Index()
        {
            return View();
        }

    }
}

barbar/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace barbar.Controllers
{
    public class CustomerController : Controller
    {
        //
        // GET: /Customer/
       
        public ActionResult Index()
        {
            return View();
        }
       // [Authorize(Roles = "Customer")]
        public ActionResult CustomerHome()
        {
            Public.LoginController m = new Public.LoginController();
            if (m.whoIsIt() != "customer") return Redirect("~/Public/Error4O4");
            return View();
        }

    }
}

barbar/Views/Customer/CustomerHome.cshtml
@{
    ViewBag.Title = "پنل مشتری";
    Layout = "~/Views/Shared/_ControlPanel.cshtml";
}

<div id="content-wrapper">
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">درخواست های بار</span>
        </div>
        <div class="panel-body">
            <div class="table-primary" id="tbll">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th id="RequestId" style="display:none">شماره</th>
                            <th>نام باربری</th>
                            <th>قیمت</th>
                            <th>نوع بار</th>
                            <th>وزن بار</th>
                            <th>آدرس مبدا</th>
                            <th>آدرس مقصد</th>
                            <th>وضعیت درخواست</th>
                        </tr>
                    </thead>
                    <tbody id="requestTbl">
            
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<script>
    init.push(function () {
        $('#jq-datatables-example').dataTable();
        $('#jq-datatables-example_wrapper .table-caption').text('Some header text');
        $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Search...');

            $.ajax({
                type: "POST",
                url: '@Url.Action("customerhomedetail", "CustomerHome")',
                dataType: 'html',
                success: function (data) {
                    if (data != null && data != "") {
                        var data = JSON.parse(data);
                        var html ="";
                        var stat="";
                        var s = "";
                       // alert(JSON.stringify(data));
                        for (var i = 0; i < data.length; i++) {
                            if(data[i].status==0){
                                s="در انتظار تایید";
                               // stat= + ' <input type="button" class="btn btn-danger btn-lg" value="لغو درخواست" />'; 
                            }else if(data[i].status==1){
                                s="تایید شده";
                            }else{
                                s="لغو شده";
                            }
                            html += ' <tr class="gradeU">'
                                        + '<td style="display:none">'+data[i].requestid+'</td>'
                                        + '<td>'+data[i].porterageName+'</td>'
                                        + '<td>'+data[i].Price+'</td>'
                                        + '<td>'+data[i].PackType+'</td>'
                                        + '<td>'+data[i].VehicleName[0].Vehicle_Weight+'</td>'
                                        + '<td>'+data[i].SourceDesti[0].SourceAddress+'</td>'
                                        + '<td>'+data[i].SourceDesti[0].destiAddress+'</td>'
                                        + '<td>'+s+'</td>'
                                  + ' </tr>';
                            
                        }
                        $('#requestTbl').html(html);
                      //  alert(JSON.stringify(data));
                    } else {
                        $('#tbll').html("درخواستی وجود ندارد");
                    }
                },
                error: function (error) {
                    //window.location.href = "../Public/Error4O4";
                    var responseTitle = $(error.responseText).filter('title').get(0);
                   
                    if (responseTitle.innerHTML =="درخواستی موجود نیست")
                        $.growl.error({ message: responseTitle.innerHTML });
                    else
                        window.location.href = "../Public/Error4O4";

                }
            });
    });

</script>