barbar/Controllers/Public/IndexController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace barbar.Controllers.Public
{
    public class IndexController : Controller
    {
        //The parameters dictionary contains a null entry for parameter 'porId' of non-nullable type 'System.Int32' for method 'System.Web.Mvc.JsonResult request(Int32, Int32, Int32, Int32, System.String, System.String)' in 'barbar.Controllers.Public.PorterageInfoController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.<br>Parameter name: parameters

        // GET: /Index/

        public ActionResult Index()
        {
           var a= HttpContext.Session["loggedIn"];
            return View();
           
        }
     
        public JsonResult Search(int weight,int value,int kind,int desti,string source)
        {
           // IList answer=null;
            Dictionary<string, IList> ans = new Dictionary<string, IList>();
              try
            {
                Models.PricesContext pc = new Models.PricesContext();
                IList price = (from i in pc.barbar where i.destination == desti && i.vehicleID == weight && i.source == source select i.price).ToList();
                //Roles.CreateRole("Customer");
                  
                //Roles.CreateRole("Porterage");
                //Roles.AddUserToRole(model.UserName, "haha");
                //Roles.IsUserInRole("haha");
                //Boolean temp = Roles.IsUserInRole("haha");
                //String[] s = Roles.GetUsersInRole("haha");
                // if(Roles.IsUserInRole("Customer")) return redirect 
                //  [Authorize(Roles="Customer")]

                Models.vehicleContext vehicle = new Models.vehicleContext();
                Models.PorterageContext porterage = new Models.PorterageContext();
                Models.packTypeContext packtype = new Models.packTypeContext();
                Models.PorterageVehicleContext porterageVehicle = new Models.PorterageVehicleContext();
                Models.PackTypePorterageContext packtypePorterage = new Models.PackTypePorterageContext();
                Models.DestiPorterageContext destiPorterage = new Models.DestiPorterageContext();
                Models.DestiContext destination = new Models.DestiContext();
                  
              //  var Kind_ID = (from i in packtype.barbar where i.Id == kind select i.Id).First();

                List<int> des = (from d in destiPorterage.barbar where d.Desti_ID == desti select d.Porterage_ID).ToList();
                List<int> veh = (from v in porterageVehicle.barbar where v.Vehicle_ID == weight && v.Vehicle_ID == value select v.Porterage_ID).ToList();
                List<int> Kind = (from k in packtypePorterage.barbar where k.IdPacktype == kind select k.IdPorterage).ToList();
                List<int> por = (from p in porterage.barbar where p.Source == source select p.Id).ToList();
               /* List<int> despor = new List<int>();
                  foreach(var d in des)
                     despor = (from dp in destiPorterage.barbar where  dp.Desti_ID == d select dp.Porterage_ID).ToList();

                  List<int> vehpor = new List<int>();
                  foreach (var d in veh)
                      vehpor = (from dp in porterageVehicle.barbar where dp.Vehicle_ID == d select dp.Porterage_ID).ToList();

                  List<int> kindpor = new List<int>();
                  foreach (var d in Kind)
                      kindpor = (from dp in packtypePorterage.barbar where dp.IdPacktype == d select dp.IdPorterage).ToList();*/
                  IList answer = des.Intersect(veh).Intersect(Kind).Intersect(por).ToList();
                  IList answeranswer = new List<IList>();
                  List<Models.Porterage> n = new List<Models.Porterage>();
                  foreach (int d in answer)
                  {
                      answeranswer.Add((from dp in porterage.barbar where dp.Id == d select new { dp.PhoneNumber, dp.Name, dp.Address, dp.Id }).ToList());
                      /*string phone = (from dp in porterage.barbar where dp.Id == d select dp.PhoneNumber).First();
                      string name = (from dp in porterage.barbar where dp.Id == d select dp.Name).First();
                      string add = (from dp in porterage.barbar where dp.Id == d select dp.Address).First();
                      int id=(from dp in porterage.barbar where dp.Id == d select dp.Id).First();
                      Models.Porterage k = new Models.Porterage(id,"0","",0,name,add,phone,"");
                     // Models.Porterage k =(Models.Porterage) (from dp in porterage.barbar where dp.Id == d select new { dp.PhoneNumber, dp.Name, dp.Address, dp.Id });
                      n.Add(k);*/

                  }

                  ans.Add("price", price);
                  ans.Add("porterages", answeranswer);
                  // IList sd = (from por in porterage.barbar join pp in packtypePorterage.barbar on por.Id equals pp.IdPorterage join pa in packtype.barbar on pp.IdPacktype equals pa.Id join vepo in porterageVehicle.barbar on por.Id equals vepo.Porterage_ID join ve in vehicle.barbar on vepo.Vehicle_ID equals ve.ID join depo in destiPorterage.barbar on por.Id equals depo.Porterage_ID join de in destination.barbar on depo.Desti_ID equals de.ID where ve.Vehicle_Weight == weight && ve.Vehicle_Value == value && de.Desti == desti && pa.Id == Kind_ID && por.Source == source select por.Name).ToList();
             //   IList sd = (from i in a.barbar join e in d.barbar on i.ID equals e.Vehicle_ID join s in b.barbar on e.Porterage_ID equals s.Id where i.Desti == desti && i.Source==source && i.Vehicle_Weight == weight && i.Vehicle_Value == value && i.Pack_Type_ID == Kind_ID select s.Name).ToList();
              
                /*foreach(var p in sd)
                {
                    answer = (from i in b.barbar where i.Id ==Convert.ToInt32( p) select i.Name).First();
                    //answer = b.barbar.SqlQuery("select Name from Porterage WHERE ID=p").ToList();
                }*/
                  return Json(ans, JsonRequestBehavior.AllowGet);
              
            }
              catch (Exception ex)
              {
                  throw ex;
              }
            
            
        }

        private void Intersect()
        {
            throw new NotImplementedException();
        }

        //
        // GET: /Index/Details/5

        public JsonResult Details()
        {

            //****************************************************************

            //Models.PricesContext p = new Models.PricesContext();
          

            //    Models.Prices pp = new Models.Prices(1 ,"اراک" , 192000 , 1);

            //    Models.Prices pp1 = new Models.Prices(1, "اراک", 2200000, 3);
            //    Models.Prices pp2 = new Models.Prices(1, "اراک", 270000, 5);
            //    Models.Prices pp3 = new Models.Prices(1, "اراک", 350000, 4);
            //    Models.Prices pp4 = new Models.Prices(1, "اراک", 490000, 6);
            //    Models.Prices pp5 = new Models.Prices(7, "اراک", 2100000, 1);
            //    Models.Prices pp6 = new Models.Prices(7, "اراک", 2700000, 3);
            //    Models.Prices pp7 = new Models.Prices(7, "اراک", 3400000, 5);
            //    Models.Prices pp8 = new Models.Prices(7, "اراک", 4400000, 4);
            //    Models.Prices pp9 = new Models.Prices(7, "اراک", 6400000, 6);
            //    Models.Prices pp10 = new Models.Prices(6, "اراک", 3500000, 1);
            //    Models.Prices pp11 = new Models.Prices(6, "اراک", 4000000, 3);
            //    Models.Prices pp12 = new Models.Prices(6, "اراک", 5300000, 5);
            //    Models.Prices pp13 = new Models.Prices(6, "اراک", 6300000, 4);
            //    Models.Prices pp14 = new Models.Prices(6, "اراک", 8700000, 6);
            //    p.barbar.Add(pp);
            //    p.barbar.Add(pp1);
            //    p.barbar.Add(pp2);
            //    p.barbar.Add(pp3);
            //    p.barbar.Add(pp4);
            //    p.barbar.Add(pp5);
            //    p.barbar.Add(pp6);
            //    p.barbar.Add(pp7);
            //    p.barbar.Add(pp8);
            //    p.barbar.Add(pp9);
            //    p.barbar.Add(pp10);
            //    p.barbar.Add(pp11);
            //    p.barbar.Add(pp12);
            //    p.barbar.Add(pp13);
            //    p.barbar.Add(pp14);
            //    p.SaveChanges();
           



            //****************************************************************

           // Models.PricesContext price = new Models.PricesContext();
            Models.packTypeContext pack = new Models.packTypeContext();
            Models.vehicleContext vehicle = new Models.vehicleContext();
            Models.DestiContext destii = new Models.DestiContext();
            Models.PorterageContext porterage = new Models.PorterageContext();

            try
            {

                IList desti = (from i in destii.barbar
                               select new
                               {
                                   i.ID,
                                   i.Desti,
                               }).ToList(); ;
                IList source = (from i in destii.barbar
                                select new
                                {
                                    i.ID,
                                    i.Desti,
                                }).ToList(); ;
                IList weight = (from i in vehicle.barbar
                                select new
                                {
                                    i.ID,
                                    i.Vehicle_Weight,
                                }).ToList();
                IList value = (from i in vehicle.barbar
                               select new
                               {

barbar/Controllers/Public/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace barbar.Controllers.Public
{
   

    public class LoginController : Controller
    {

        public String SignIn(string username, string password)
        {

            try
            {
                Models.userContext a = new Models.userContext();
                Models.PorterageContext b = new Models.PorterageContext();

           /*     var md = new HMACMD5();
                var salt = System.Text.Encoding.UTF8.GetBytes(password);
                var Pass1 = md.ComputeHash(salt);*/
             
                
                //  var u = a.barbar.Where<Models.User>(bb => bb.UserName == username && bb.Password == password);
                int u = (from aa in a.barbar where aa.UserName == username && aa.Password == password select aa.UserName).Count();
                var p = (from aa in b.barbar where aa.UserName == username && password == aa.Password select aa.Id).Count();
                if (u > 0)
                {
                    Session["loggedIn"] = username;
                    return "../Customer/CustomerHome";
                    //RedirectToAction("CustomerHome", CustomerController);//controler eshtebah
                }
                else if (p > 0)
                {
                    Session["loggedIn"] = username;
                    return "../Porterage/PorterageHome";
                }
                else
                    throw new Exception("Your username or Password is Invalid");

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }


        public string whoIsIt() {


            
         try
            {
             string username = HttpContext.Session["LoggedIn"].ToString();
                Models.userContext a = new Models.userContext();
                Models.PorterageContext b = new Models.PorterageContext();

                int u = (from aa in a.barbar where aa.UserName == username select aa.UserName).Count();
                var p = (from aa in b.barbar where aa.UserName == username  select aa.Id).Count();
                if (u > 0)
                {
                 
                    return "customer";
                    //RedirectToAction("CustomerHome", CustomerController);//controler eshtebah
                }
                else if (p > 0)
                {
                    
                    return "porterage";
                }
                else
                    throw new Exception("شما هنور وارد سایت نشده اید");

            }
         catch (Exception ex)
         {

             return "null";
         }
        
        
        
        }

        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Login/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Login/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Login/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Login/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Login/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Login/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Login/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

barbar/Controllers/Public/PorterageListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace barbar.Controllers
{
    public class PorterageListController : Controller
    {
        //
        // GET: /PorterageList/

        public ActionResult PorterageList()
        {
            return View();
        }

    }
}

barbar/Controllers/PublicController.cs
using barbar.Filters;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace barbar.Controllers
{
    //[Authorize]
   // [InitializeSimpleMembership]
    public class PublicController : Controller
    {
        //
        // GET: /Public/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PorterageInfo()
        {
            ViewBag.Id=(Request.Params["Id"]);
            ViewBag.source = (Request.Params["source"]);
            ViewBag.desti = (Request.Params["desti"]);
            ViewBag.type = (Request.Params["type"]);
            ViewBag.weight = (Request.Params["weight"]);
            ViewBag.value = (Request.Params["value"]);
            ViewBag.Title = "مشخصات باربری";
            return View();
        }
        public ActionResult PorterageList()
        {
            return View();
        }
        //[AllowAnonymous]
        public ActionResult Login()
        {
            ViewBag.Title = "ورود";
            return View();
        }
        public ActionResult SignUp()
        {
            ViewBag.Title = "ثبت نام";
            return View();
        }
        public ActionResult Error4O4()
        {
            //ViewBag.Title = "ثبت نام";
            return View();
        }

    }
}

barbar/Views/Public/Error4O4.cshtml
@{
    ViewBag.Title = "خطا";
    
}
<title> @ViewBag.Title</title>
<h2 style="text-align:center;margin-top:15%">صفحه مورد نظر وجود ندارد</h2>

barbar/Views/Public/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<title>@ViewBag.Title</title>
<div class="signup-container" style="width:99%;">
    @Scripts.Render("~/Scripts/bottom-js")
 
    <div class="panel panel-primary panel-dark">
        <div class="panel-heading ">
            <span class="panel-title text-bold" style="color:white"><i class="fa fa-link"></i>&nbsp;&nbsp;&nbsp;مشخصات بار</span>
        </div>

        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "PackFrm" }))
{
    <div class="panel-body">

        <div class="row">
            <div class="col-md-4">
                <label class="control-label col-md-2">وزن</label>
                <div class="input-group col-md-10">
                    <span class="input-group-addon text-warning"><i class="fa fa-circle"></i></span>
                    <select id="weight_select" class="form-control" name="weight"></select>
                </div>
            </div>

            <div class="col-md-4">
                <label class="control-label col-md-2">نوع بار</label>
                <div class="input-group col-md-10">
                    <span class="input-group-addon text-warning"><i class="fa fa-circle"></i></span>
                    <select id="type_select" class="form-control" name="kind"></select>
                </div>
            </div>

            <div class="col-md-4">
                <label class="control-label col-md-2">حجم</label>
                <div class="input-group col-md-10">
                    <span class="input-group-addon text-warning"><i class="fa fa-circle"></i></span>
                    <select class="form-control" id="dimension_select" name="value"></select>
                </div>
            </div>
        </div><br><br>
        <div class="row">
            <div class="col-md-4">
                <label class="control-label col-md-2">مبدا</label>
                <div class="input-group col-md-10">
                    <span class="input-group-addon text-warning"><i class="fa fa-circle"></i></span>
                    <select id="source_select" class="form-control" name="source"></select>
                </div>
            </div>
            <div class="col-md-4">
                <label class="control-label col-md-2">مقصد</label>
                <div class="input-group col-md-10">
                    <span class="input-group-addon text-warning"><i class="fa fa-circle"></i></span>
                    <select id="dest_select" class="form-control" name="desti"></select>
                </div>
            </div>

            <div class="col-md-4">
                <input type="button" class="btn  btn-info col-md-12" id="SeeResultBtn" value="مشاهده ی نتیجه">

            </div>
        </div>
        <div class="row">
            <span>قیمت حدودی بار شما:</span><span id="price"></span>
        </div>
    </div>
}
    </div>
   

    <div class="panel widget-messages-alt panel-primary panel-dark" id="porteragelist" style="display:none">
        <div class="panel-heading">
            <span class="panel-title text-bold" style="color:white"><i class="fa fa-link"></i>&nbsp;&nbsp;&nbsp;لیست باربری ها</span>
        </div> 
        <div class="panel-body padding-sm">
            <div class="messages-list" id="porteragedetail">
               


            </div> 
            <a href="#" class="messages-link">ادامه ...</a>
        </div> 
    </div> 
</div>
<script>
    init.push(function () {
        $('#uidemo-modals-effects-btn').on('click', function () {
            var $modal = $('#uidemo-modals-effects-template').clone(true);
            $modal.find('> div').addClass('modal-dialog modal-sm animated ' + $('#uidemo-modals-effects-select').find(":selected").attr('value'));
            $modal.modal('show');
        });


        $.ajax({
            type: "get",
            url: '@Url.Action("Details", "Index")',
            dataType: 'html',
        
            success: function (data) {
                var data = JSON.parse(data);
                //   alert(JSON.stringify(data));
                var packtype = data.Kind;
                var desti = data.Destination;
                var Value = data.Value;
                var Source = data.Source;
                var weight = data.Weight;
                for (var i = 0; i < packtype.length; i++) {
                    var opt = new Option(packtype[i].TypeName, packtype[i].Id);
                    $('#type_select').append(opt);
                }
                for (var i = 0; i < desti.length; i++) {
                    var opt = new Option(desti[i].Desti, desti[i].ID);
                    $('#dest_select').append(opt);
                }
                for (var i = 0; i < Source.length; i++) {
                    var opt = new Option(Source[i].Desti, Source[i].Desti);
                    $('#source_select').append(opt);
                }
                for (var i = 0; i < weight.length; i++) {
                    var opt = new Option(weight[i].Vehicle_Weight, weight[i].ID);
                    $('#weight_select').append(opt);
                }
                for (var i = 0; i < Value.length; i++) {
                    var opt = new Option(Value[i].Vehicle_Value, Value[i].ID);
                    $('#dimension_select').append(opt);
                }
            },
            error: function (error) {
                var responseTitle = $(error.responseText).filter('title').get(0);
                $.growl.error({ message: responseTitle.innerHTML });
            }
        });
       
    });
   
    window.PixelAdmin.start(init);

    $('#SeeResultBtn').click(function () {
       // alert("hi");
              $.ajax({
                 type: "POST",
                 url: '@Url.Action("Search", "Index")',
                 dataType: 'html',
                 data: $('#PackFrm').serialize(),
                 success: function (data) {
                     var data = JSON.parse(data);
                   //  alert(JSON.stringify(data));
                     
                     if (data.price !=[] && data.price !="")
                        $('#price').html(data.price);
                      data = data.porterages;
                     var html="";
                     for (var i = 0; i < data.length; i++) {
                         //alert(JSON.stringify(data[i][0]))
                         html += '<div class="message">'
                             + '            <img src="~/Images/avatar.png" alt="" class="message-avatar">'
                             + '            <a href="@Url.Action("PorterageInfo", "Public")?Id='+data[i][0].Id+'&source='+$('#source_select').val()+'&desti='+$('#dest_select').val()+'&type='+$('#type_select').val()+'&weight='+$('#weight_select').val()+'&value='+ $('#dimension_select').val()+'" class="message-subject">' + data[i][0].Name + '</a>'
                             + '            <div class="message-description">' + data[i][0].Address +"-" +data[i][0].PhoneNumber+' </div>'
                             + '       </div>';
                     }
                     $("#porteragedetail").html(html);
                     $('#porteragelist').show();
                 },
                 error: function (error) {
                     var responseTitle = $(error.responseText).filter('title').get(0);
                     $.growl.error({ message: responseTitle.innerHTML });
                 }
             });
             });


</script>        
    

barbar/Views/Public/Login.cshtml
@{
    ViewBag.Title = "ورود";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<title>@ViewBag.Title</title>
<style>
    #signup-demo {
        position: fixed;
        right: 0;
        bottom: 0;
        z-index: 10000;
        background: rgba(0,0,0,.6);
        padding: 6px;
        border-radius: 3px;
    }

        #signup-demo img {
            cursor: pointer;
            height: 40px;
        }

            #signup-demo img:hover {
                opacity: .5;
            }

        #signup-demo div {
            color: #fff;
            font-size: 10px;
            font-weight: 600;
            padding-bottom: 6px;
        }
</style>



<div class="signup-container">
    <!-- Header -->
    <div class="signup-header">
        <a href="index.html" class="logo">
            باربر
        </a> <!-- / .logo -->

    </div>
    <!-- / Header -->
    <!-- Form -->
    <div class="signup-form">
    
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "loginFrm" }))
        {
            <div >

                <div class="signup-text">
                    <span>ورود به حساب کاربری</span>
                </div>

                <div class="form-group w-icon">
                    <input type="text" name="username" id="username_id" class="form-control input-lg" placeholder="نام کاربری">
                    <span class="fa fa-user signup-form-icon"></span>
                </div>

                <div class="form-group w-icon">
                    <input type="password" name="password" id="password_id" class="form-control input-lg" placeholder="رمز عبور">
                    <span class="fa fa-lock signup-form-icon"></span>
                </div>

                <div class="form-actions">
                    <input type="button" value="ورود" class="signup-btn bg-primary" id="LoginBtn">
                </div>
            </div>
        }
        <div id="message" style="padding:20px;color:red"></div>
    </div>
</div>

<div class="have-account">
    Not a member? <a href="SignUp">Sign Up</a>
</div>

@Scripts.Render("~/Scripts/bottom-js")
<script type="text/javascript">


        init.push(function () {
                  $("#signup-form_id").validate({ focusInvalid: true, errorPlacement: function () { } });
        });

        window.PixelAdmin.start(init);
        
        $('#LoginBtn').click(function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("SignIn", "Login")',
                dataType: 'html',
                data: $('#loginFrm').serialize(),
                success: function (data) {
                    window.location.href = data;
                  //  $('#message').html(JSON.stringify(data));
                },
                error: function (error) {
                    var responseTitle = $(error.responseText).filter('title').get(0);
                    $.growl.error({ message: responseTitle.innerHTML });
                }
            });
        });
</script>