barbar/Models/Porterage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Web.Security;

namespace barbar.Models {
  public class Porterage  {
      [Key]
      [Column(Order = 0)]
      [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Password { get; set; }
        public string Source { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public double Rank { get; set; }
      //  public barbar.Models.PackType[] PorteragePackType { get; set; }

        [Index(IsUnique = true)]
        public int Code { get; set; }
        public string OwnerName { get; set; }
        public int PorteragePriceId { get; set; }
        public int OwnerIdentityNumber { get; set; }
        //public string LogoImage { get; set; }
        public int packTypeId { get; set; }
     //   private Models.PorterageVehicle porterageVehicle { get; set; }
        public int porterageVehicleId { get; set; }
       // private PorteragePrice porteragePrice { get; set; }
        public int customerRequestId { get; set; }
        //private Models.Contract contract { get; set; }
        public int driverRequestId { get; set; }
        public string status { get; set; }
       // private Models.DriverRequest driverRequest { get; set; }
      //  private CustomerRequest customerRequest { get; set; }
     //   private PackType packType { get; set; }
        public Porterage(int code,string email, string owner,int ownerid,string name, string addre,string phone,string source) 
        {
            OwnerIdentityNumber = ownerid;
            //LogoImage = logo;
            Code = code;
            Email = email;
            OwnerName = owner;
            Name = name;
            Address = addre;
            PhoneNumber = phone;
            Source = source;
        }
  }
    public class PorterageContext : DbContext
    {
        public DbSet<Porterage> barbar { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Porterage>().ToTable("Porterage");
      

            base.OnModelCreating(modelBuilder);
        }
    }

}

barbar/Controllers/Porterage/PorterageHomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace barbar.Controllers
{
    public class PorterageHomeController : Controller
    {

        public JsonResult porteragehomeDetail() {

            string username;
            try
            {
                username = HttpContext.Session["LoggedIn"].ToString();
            }
            catch (Exception e) { return Json("E" , JsonRequestBehavior.AllowGet); }
            try{

            Models.userContext u = new Models.userContext();
            Models.PorterageContext porterage = new Models.PorterageContext();
            Models.CustomerRequestContext request = new Models.CustomerRequestContext();
            Models.vehicleContext vehicle = new Models.vehicleContext();
            Models.packTypeContext pack = new Models.packTypeContext();
            Models.PricesContext prices = new Models.PricesContext();
            Models.DestiContext desti = new Models.DestiContext();
           // string username = HttpContext.Session["LoggedIn"].ToString();
            int ID = (from d in porterage.barbar where d.UserName == username select d.Id).First();
            List<int> requestids=(from d in request.barbar where d.PorterageID==ID select d.Id).ToList();
            string source = (from d in porterage.barbar where d.UserName == username select d.Source).First();
            IList<Dictionary<string, IList>> answer = new List<Dictionary<string, IList>>();
            foreach (var dd in requestids)
            {
                Dictionary<string, IList> ha = new Dictionary<string, IList>();

                IList idd = new List<int>();
                idd.Add(dd);

               // int porId = (from i in request.barbar where i.CustomerID == username select i.PorterageID).First();
               int porid = (from i in porterage.barbar where i.UserName == username select i.Id).First();
               string porname1 = (from i in request.barbar where i.PorterageID == porid select i.CustomerID).First();
               IList porname = (from i in u.barbar where i.UserName == porname1 select new {i.FirstName , i.LastName }).ToList();
                IList status = (from d in request.barbar where d.Id == dd select d.Status).ToList();
                IList sourcedesti = (from d in request.barbar where d.Id == dd select new { d.SourceAddress, d.destiAddress }).ToList();
                int vehicleid = (from d in request.barbar where d.Id == dd select d.VehicleId).First();
                IList vehicleName = (from d in vehicle.barbar where d.ID == vehicleid select d.Vehicle_name).ToList();
                int packtypeid = (from d in request.barbar where d.Id == dd select d.PackTypeId).First();
                IList packtypename = (from d in pack.barbar where d.Id == packtypeid select d.TypeName).ToList();
                int destiId = (from d in request.barbar where d.Id == dd select d.DestinationId).First();
                IList price = (from d in prices.barbar where d.source == source && d.destination == destiId && d.vehicleID == vehicleid select d.price).ToList();
                ha.Add("SourceDesti", sourcedesti);
                ha.Add("VehicleName", vehicleName);
                ha.Add("PackType", packtypename);
                ha.Add("Price", price);
                ha.Add("porterageName", porname);
                ha.Add("requestid", idd);
                ha.Add("status", status);
                answer.Add(ha);
            }
                  return Json(answer, JsonRequestBehavior.AllowGet);
            }
                catch(Exception e){
                
                throw e;
                }
                
            
           
    
          
        
        }

        public JsonResult update(int id) {
            try
            {
            var username = HttpContext.Session["LoggedIn"];
            Models.userContext u = new Models.userContext();
            Models.CustomerRequestContext por = new Models.CustomerRequestContext();
            Models.PorterageContext p = new Models.PorterageContext();
            var name = (from i in p.barbar where i.UserName == username select i.Name).First();
            var request = (from i in por.barbar where i.Id == id select i.CustomerID).First();
            var email = (from i in u.barbar where i.UserName == request select i.Email).First();

            
            var it = por.barbar.Find(id);
            it.Status = 1;
            por.Entry(it).State = EntityState.Modified;
            por.SaveChanges();

           
                MailMessage mail = new MailMessage();


                mail.From = new MailAddress("talayeh.riahi@gmail.com");
                mail.To.Add(new MailAddress(email));
                mail.Subject = ("تایید باربری");
                mail.Body = " درخواست شما را تایید کرد بنابراین جهت عقد قرارداد به سایت مراجعه کنید "+ name +"باربری ";
                mail.IsBodyHtml = true;
                mail.DeliveryNotificationOptions = DeliveryNotificationOptions.OnFailure;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential("talayeh.riahi@gmail.com", "tala1374");// Enter seders User name and password
                smtp.EnableSsl = true;
                /*ServicePointManager.ServerCertificateValidationCallback =
                                        delegate(object s, X509Certificate certificate,
                                                 X509Chain chain, SslPolicyErrors sslPolicyErrors)
                                        { return true; };*/


                smtp.Send(mail);

                return null;

            }
            catch (Exception ee)
            {
                throw new Exception("مشکل در فرستادن ایمیل");
            }
            
        
        
        }
        public JsonResult getuser()
        {

            try
            {
                Models.PorterageContext p = new Models.PorterageContext();
                string username = HttpContext.Session["LoggedIn"].ToString();
                string name = (from i in p.barbar where i.UserName == username select i.Name).First();

                return Json(name, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e) { throw e; }

        }
        //
        // GET: /PorterageHome/

        public ActionResult PorterageHome()
        {
            return View();
        }

        //
        // GET: /PorterageHome/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /PorterageHome/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PorterageHome/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PorterageHome/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /PorterageHome/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PorterageHome/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /PorterageHome/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

barbar/Controllers/PorterageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace barbar.Controllers
{
    public class PorterageController : Controller
    {
        //
        // GET: /Porterage/ 

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PorterageHome()
        {
            ViewBag.Message = "home";
            if (Roles.IsUserInRole("Customer")) return Redirect("~/Public/Error4O4");

            return View();
        }
       
    }
}

barbar/Views/Porterage/PorterageHome.cshtml
@{
    ViewBag.Title = "پنل باربری";
    Layout = "~/Views/Shared/_ControlPanel.cshtml";
}

<div id="content-wrapper">
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">درخواست های مشتریان</span>
        </div>
        <div class="panel-body">
            <div class="table-primary" id="tbll">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" >
                    <thead>
                        <tr>
                            <th id="RequestId" style="display:none">شماره</th>
                            <th>نام مشتری</th>
                            <th>قیمت</th>
                            <th>نوع بار</th>
                            <th>نوع وسیله ی نقلیه</th>
                            <th>آدرس مبدا</th>
                            <th>آدرس مقصد</th>
                            <th>وضعیت درخواست</th>
                        </tr>
                    </thead>
                    <tbody id="requestTbl">
                      
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
</div>
<script>
    init.push(function () {
        $('#jq-datatables-example').dataTable();
        $('#jq-datatables-example_wrapper .table-caption').text('Some header text');
        $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
        getDetail();
           
        
    });
    function getDetail() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("porteragehomeDetail", "PorterageHome")',
            dataType: 'html',
            success: function (data) {
                if (data != null && data != "") {
                    var data = JSON.parse(data);
                    if (data == "E")
                        window.location.href = "../Public/Login";
                   // alert(JSON.stringify(data));
                    var html = "";
                    for (var i = 0; i < data.length; i++) {
                        var stat = "";
                        if (data[i].status == 0) {
                            s = "در انتظار تایید";
                            stat = '   <div class="btn-toolbar" role="toolbar">'
                                        + '       <div class="btn-group">'
                                        + '            <input type="button" class="btn btn-success btn-lg" value="ثبت درخواست" onclick="ChaneStatuse(\'' + data[i].requestid + '\')"/>'
                                        + '            <input type="button" class="btn btn-danger btn-lg" value="رد درخواست" />'
                                        + '        </div>'
                                        + '    </div>';
                        } else if (data[i].status == 1) {
                            s = "تایید شده";
                        } else {
                            s = "لغو شده";
                        }
                        html += ' <tr class="gradeU">'
                                    + '<td style="display:none">' + data[i].requestid + '</td>'
                                    + '<td>' + data[i].porterageName[0].FirstName + " " + data[i].porterageName[0].LastName + '</td>'
                                    + '<td>' + data[i].Price + '</td>'
                                    + '<td>' + data[i].PackType[0] + '</td>'
                                    + '<td>' + data[i].VehicleName[0] + '</td>'
                                    + '<td>' + data[i].SourceDesti[0].SourceAddress + '</td>'
                                    + '<td>' + data[i].SourceDesti[0].destiAddress + '</td>'
                                    + '<td>' + s + stat + '</td>'
                              + ' </tr>';

                    }
                    $('#requestTbl').html(html);
                    // alert(JSON.stringify(data));
                } else {
                    $('#tbll').html("درخواستی وجود ندارد");
                }
            },
            error: function (error) {
                window.location.href = "../Public/Error4O4";
                var responseTitle = $(error.responseText).filter('title').get(0);
                $.growl.error({ message: responseTitle.innerHTML });
            }
        });

    }
    function ChaneStatuse(id) {
      //  alert(id);
        $.ajax({
            type: "POST",
            url: '@Url.Action("update", "PorterageHome")',
            dataType: 'html',
            data: { id: id },
            success: function (data) {
                $.growl.notice({ message: "درخواست با موفقیت ثبت شد" });
                getDetail();
            },
            error: function (error) {
                var responseTitle = $(error.responseText).filter('title').get(0);
                $.growl.error({ message: responseTitle.innerHTML });
            }
        });
    }
</script>